### PR TITLE
feat(serde): borsh

### PR DESCRIPTION
**Pull request by dzmitry-lahoda**

### CODE REVIEW

**Comment by isaacholt100** [comment]
Thanks for this PR @dzmitry-lahoda! Sorry for taking a while to respond to this, I'm very busy at the moment. I'll merge this into the `latest` branch, add a few changes (basically just increase the version number), then publish a new version. Is this a feature you need soon/now? If so then I'll do my best to do this ASAP, can't promise exactly when unfortunately, it should be within a week though I hope.

**Comment by dzmitry-lahoda** [comment]
no worries, not ASAP. we use bnum as direct dep only, so fork works for us clean. thanks

**Comment by isaacholt100** [comment]
@dzmitry-lahoda I will publish 0.12.0 soon with borsh support - looking at the line you added for it in Cargo.toml, I was wondering whether the "rc" and "std" features are necessary? Everything seems to compile without these enabled. If you could let me know ASAP that would be appreciated, as then I can include borsh in the next version.

**Comment by dzmitry-lahoda** [comment]
you are right, `"rc", "std",` are no needed.  that is just line from our repo. sorry.

**Comment by isaacholt100** [comment]
Thanks for replying so quickly!

**Pull request merged**
