### PR TITLE
add set_bit to buint

### PR DESCRIPTION
**Pull request by krakow10**
Hi, is there room for more digit manipulation without needing to copy the whole value?  This is one thing I would like to have.

### CODE REVIEW

**Comment by isaacholt100** [comment]
Hi @krakow10, thanks for this pull request. I'm happy to add more digit manipulation, what do you specifically want? I will merge this PR, but first could you add documentation for `set_bit` by creating a `set_bit` macro in `doc/mod.rs`, use the `bit` macro as an example, then add `#[doc = doc::set_bit!(U 256)]` to the definition instead of `#[doc = doc::bit!(U 256)]`. Thanks.

**Comment by krakow10** [comment]
I wrote a documentation like you requested.  Can you think of a better way to set the bit?  For example, do you think `$Digit::from(value)` is problematic and should be done differently?

> I'm happy to add more digit manipulation, what do you specifically want?

I thought I would come up with more digit manipulation needs, but I didn't run into anything else that inspired a useful method.  I will propose more changes later if I think of something useful, thanks.

P.S. I couldn't compile or test this because of the unstable features

**Comment by isaacholt100** [comment]
Sorry for the very slow response time @krakow10, I've just come back from a holiday. Thanks for adding the documentation, I will merge this now. Sorry about the compilation error when trying to test - annoyingly, the nightly compiler seems to have recently dropped const trait support, which is what was causing that issue. I'm going to make those traits non-const for now. I'll publish 0.12.0 with both these changes either today or tomorrow, hopefully.

**Comment by isaacholt100** [comment]
I think there may be a slight error in your code actually, as applying `& (1 << shift)` will zero out other bits - I've modified it slightly so that it's fully correct, by doing
```rs
if value {
    *digit |= (1 << shift);
} else {
    *digit &= !(1 << shift);
}
```

**Comment by krakow10** [comment]
I think it was supposed to be a reverse mask, but I forgot `!`.  Like this:
```rust
*digit = *digit & !(1 << shift) | ($Digit::from(value) << shift)
```
Saves a branch that way.

**Comment by isaacholt100** [comment]
Ah yeah I see, I think a branch is unavoidable though as `$Digit::from(value)` uses one.

**Pull request merged**
